name: Sync to Hugging Face hub
on:
  push:
    branches: [sync-hf]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://tmarafon2:$HF_TOKEN@huggingface.co/spaces/tmarafon2/Mistral_7B_API main